import { useState } from 'react';
import { streamPostSSE } from '../lib/sseClient.js';
import { apiUrl } from '../lib/api.js';

export default function InvestmentMemoCard({ report, onMemoReady }) {
  const [state, setState] = useState('idle'); // idle | running | done | error
  const [memo, setMemo] = useState('');
  const [error, setError] = useState(null);

  async function generate() {
    setState('running');
    setMemo('');
    setError(null);
    let buffer = '';
    try {
      await streamPostSSE(
        apiUrl('/api/investment-memo'),
        { report },
        {
          delta: (data) => {
            buffer += data.text || '';
            setMemo(buffer);
          },
          memo: (data) => {
            const final = data?.markdown || buffer;
            setMemo(final);
            setState('done');
            onMemoReady?.(final);
          },
          error: (data) => {
            setError(data?.message || 'Memo generation failed');
            setState('error');
          },
        },
      );
    } catch (err) {
      setError(err.message || 'Memo generation failed');
      setState('error');
    }
  }

  return (
    <section className="card border-l-4 border-l-claude">
      <header className="mb-3 flex flex-wrap items-baseline justify-between gap-2">
        <div>
          <p className="card-title">Investment memo</p>
          <h3 className="mt-1 font-display text-lg font-bold">
            Structured memorandum for an investment committee
          </h3>
          <p className="mt-1 text-sm text-slate-600">
            Pulls every data point in this report into a formal exec summary, market context,
            financial summary, risks, and a proceed / decline recommendation. Generated by Claude in
            ~10 seconds. Output is appended as page 2 of the Word doc download.
          </p>
        </div>
        <button
          type="button"
          className={state === 'running' ? 'btn-soft' : 'btn-primary'}
          onClick={generate}
          disabled={state === 'running'}
        >
          {state === 'idle' && '✍️ Draft investment memo'}
          {state === 'running' && 'Drafting…'}
          {state === 'done' && 'Re-draft memo'}
          {state === 'error' && 'Try again'}
        </button>
      </header>

      {state === 'error' && (
        <p className="rounded-lg bg-crit-bg p-3 text-sm text-crit-text">{error}</p>
      )}

      {(state === 'running' || state === 'done') && (
        <div className="rounded-xl border border-cream-200 bg-cream-50 p-4">
          <pre className="whitespace-pre-wrap font-sans text-sm leading-relaxed text-ink">
            {memo || 'Drafting…'}
          </pre>
        </div>
      )}
    </section>
  );
}
